//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ecomerce2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int MaSP { get; set; }
        public int MaHD { get; set; }
        public string SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
